name: Preubas con Pytest
on:
  push:
    branches: ["main", "branch1"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    #Cuando se inicie manualmente desde la pestaña "Actions" en GitHub
jobs:
  Pytest:
    runs-on: ububtu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Instala Pytest
        run: pip install pytest
      - name: Correr pruebas con Pytest
        run:
          pytest tests/integracion_test.py -v
